import React from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';

const SEO = ({ pageName }) => {
  return (
    <Head>
      <title>Baobab | {pageName}</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};

SEO.propTypes = {
  pageName: PropTypes.string.isRequired,
};

export default SEO;
